# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "MongoDBU_M202"
  config.vm.box_url = "https://s3.amazonaws.com/edu-downloads.10gen.com/m202/mongodbu.box"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
  
    vb.name = "MongoDBU"
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]  
  end

end
